name: media_module
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # pip_view: ^0.9.7
  video_player: ^2.9.2
  # camera: ^0.11.0+2
  camera: 0.10.6
  path_provider: ^2.1.4
  path: ^1.9.0
  floating: ^4.0.1
  uuid: ^4.5.1
  record: ^5.1.2
  audio_waveforms: ^1.1.1
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6

  video_thumbnail:
    path: ../video_thumbnail
  pip_view:
    path: ../pip_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  video_player_android: 2.7.1
  camera_android_camerax: ^0.6.9+2


flutter:
  uses-material-design: true
